/**
 * AI Symptom Checker Screen
 * Structured Input -> Results -> Disease Info flow aligned to app design system.
 */

import React, { useCallback, useMemo, useState } from "react";
import { useAuth } from "@/context/AuthContext";
import {
  ActivityIndicator,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  StatusBar,
} from "react-native";
import {
  SafeAreaView,
  useSafeAreaInsets,
} from "react-native-safe-area-context";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  Clock,
  Info,
  Plus,
  Sparkles,
  Stethoscope,
  X,
} from "lucide-react-native";

import { theme, healthColors } from "@/theme";
import {
  Button,
  Card,
  EmptyState,
  Input,
  SectionHeader,
} from "@/components/common";
import { AIIcon } from "@/components/common/CustomIcons";
import { getScreenPadding } from "@/utils/responsive";
import { handleSmartBack } from "@/utils/navigation";
import { showError, parseError, logError } from "@/utils/errorHandler";
import Routes from "@/navigation/routes";
import { useNetworkStatus } from "@/utils/offlineHandler";
import aiService from "@/services/ai.service";
import { queryKeys } from "@/config/reactQueryConfig";
import { useTranslation } from 'react-i18next';

const COMMON_SYMPTOMS = [
  "Fever",
  "Headache",
  "Cough",
  "Fatigue",
  "Body ache",
  "Sore throat",
  "Runny nose",
  "Nausea",
];

const SEVERITY_OPTIONS = [
  { value: "mild", label: "Mild", color: healthColors.success.main },
  { value: "moderate", label: "Moderate", color: healthColors.warning.main },
  { value: "severe", label: "Severe", color: healthColors.error.main },
];


const AISymptomChecker = ({ navigation }) => {
  const { t } = useTranslation();
  const insets = useSafeAreaInsets();
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const { isConnected } = useNetworkStatus();

  const [selectedSymptoms, setSelectedSymptoms] = useState([]);
  const [symptomDraft, setSymptomDraft] = useState("");
  const [duration, setDuration] = useState("");
  const [severity, setSeverity] = useState("moderate");
  const [validationMessage, setValidationMessage] = useState("");
  const [results, setResults] = useState(null);
  const [screenError, setScreenError] = useState(null);

  const analysisQueryKey = useMemo(
    () => queryKeys.ai.symptomAnalysis(user?.id),
    [user?.id]
  );

  const normalizedSymptoms = useMemo(
    () => selectedSymptoms.map((item) => item.trim()).filter(Boolean),
    [selectedSymptoms]
  );

  const isFormReady = normalizedSymptoms.length > 0;

  const analysisMutation = useMutation({
    mutationFn: (payload) => aiService.analyzeSymptoms(payload),
    onSuccess: (response, payload) => {
      const analysis = response?.analysis || null;
      setResults(analysis);
      setScreenError(null);
      setValidationMessage("");

      queryClient.setQueryData(analysisQueryKey, {
        analysis,
        submittedAt: new Date().toISOString(),
        payload,
      });
      queryClient.invalidateQueries({ queryKey: analysisQueryKey });
    },
    onError: (error) => {
      const message =
        parseError(error) || "Unable to analyze symptoms right now.";
      logError(error, {
        context: "AISymptomChecker.analyzeSymptoms",
        selectedSymptomsCount: normalizedSymptoms.length,
      });
      setScreenError(message);
      showError(message);
    },
    retry: 1,
  });

  const conditionList = useMemo(
    () =>
      [...(results?.possibleConditions || [])].sort(
        (a, b) => (b?.probability || 0) - (a?.probability || 0)
      ),
    [results]
  );

  const topCondition = conditionList[0] || null;
  const diseaseInfo = useMemo(() => {
    const fallback = {
      overview: "This condition summary is generated by AI. Please verify with a clinician for diagnosis and treatment.",
      symptoms: ["Symptoms may vary by patient and severity"],
      causes: ["Multiple possible causes depending on clinical history"],
      treatment: ["Consult a doctor for a personalized treatment plan"],
    };
    return topCondition?.details || fallback;
  }, [topCondition]);

  const handleToggleCommonSymptom = useCallback((symptom) => {
    setValidationMessage("");
    setResults(null);
    setSelectedSymptoms((prev) => {
      const exists = prev.some(
        (item) => item.toLowerCase() === symptom.toLowerCase()
      );
      return exists
        ? prev.filter((item) => item.toLowerCase() !== symptom.toLowerCase())
        : [...prev, symptom];
    });
  }, []);

  const handleAddCustomSymptoms = useCallback(() => {
    const tokens = symptomDraft
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean);

    if (!tokens.length) {
      setValidationMessage("Add at least one valid symptom before continuing.");
      return;
    }

    setValidationMessage("");
    setResults(null);
    setSelectedSymptoms((prev) => {
      const existingLower = new Set(prev.map((item) => item.toLowerCase()));
      const unique = tokens.filter(
        (item) => !existingLower.has(item.toLowerCase())
      );
      return [...prev, ...unique];
    });
    setSymptomDraft("");
  }, [symptomDraft]);

  const handleRemoveSymptom = useCallback((symptom) => {
    setValidationMessage("");
    setResults(null);
    setSelectedSymptoms((prev) => prev.filter((item) => item !== symptom));
  }, []);

  const handleAnalyze = useCallback(async () => {
    if (!normalizedSymptoms.length) {
      const message = "Please select or add at least one symptom to continue.";
      setValidationMessage(message);
      showError(message);
      return;
    }

    if (!isConnected) {
      const message = "No internet connection. Reconnect and try again.";
      setValidationMessage(message);
      showError(message);
      return;
    }

    setValidationMessage("");
    setScreenError(null);

    await analysisMutation.mutateAsync({
      symptoms: normalizedSymptoms,
      duration: duration.trim(),
      severity,
    });
  }, [analysisMutation, duration, isConnected, normalizedSymptoms, severity]);

  const handleClearAll = useCallback(() => {
    setSelectedSymptoms([]);
    setSymptomDraft("");
    setDuration("");
    setSeverity("moderate");
    setValidationMessage("");
    setResults(null);
    setScreenError(null);
    queryClient.removeQueries({ queryKey: analysisQueryKey });
  }, [analysisQueryKey, queryClient]);

  if (screenError && !results) {
    throw new Error(screenError || "Unknown Error");
  }

  return (
    <SafeAreaView style={styles.container} edges={["top", "left", "right"]}>
      <StatusBar
        barStyle="dark-content"
        backgroundColor={healthColors.background.card}
      />

      <View
        style={[styles.header, { paddingTop: insets.top + theme.spacing.xs }]}
      >
        <TouchableOpacity
          onPress={() => handleSmartBack(navigation, "PatientTabs")}
          style={styles.headerButton}
          accessibilityRole="button"
          accessibilityLabel="Go back"
          hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
        >
          <ArrowLeft
            size={theme.iconSizes.md}
            color={healthColors.text.primary}
          />
        </TouchableOpacity>

        <View style={styles.headerTitleWrap} pointerEvents="none">
          <Text style={styles.headerTitle} numberOfLines={1}>
            {t('ai_symptom_checker')}
          </Text>
          <Text style={styles.headerSubtitle} numberOfLines={2}>
            {t('analyze_symptoms_review_likely')} symptoms, review likely conditions, and read disease
            guidance
          </Text>
        </View>

        <View style={styles.headerButton} />
      </View>

      <ScrollView
        contentContainerStyle={[
          styles.scrollContent,
          {
            paddingBottom: Math.max(
              insets.bottom + theme.spacing.md,
              theme.spacing.xl
            ),
          },
        ]}
        keyboardShouldPersistTaps="handled"
      >
        <View style={styles.contentColumn}>
          <Card style={styles.sectionCard}>
            <SectionHeader title="1. Input Symptoms" />

            <Text style={styles.fieldLabel}>{t('quick_select')}</Text>
            <View style={styles.symptomGrid}>
              {COMMON_SYMPTOMS.map((symptom) => {
                const isSelected = selectedSymptoms.some(
                  (item) => item.toLowerCase() === symptom.toLowerCase()
                );
                return (
                  <TouchableOpacity
                    key={symptom}
                    style={[
                      styles.symptomChip,
                      isSelected && styles.symptomChipSelected,
                    ]}
                    onPress={() => handleToggleCommonSymptom(symptom)}
                    accessibilityRole="button"
                    accessibilityLabel={`Toggle ${symptom}`}
                    accessibilityState={{ selected: isSelected }}
                  >
                    <Text
                      style={[
                        styles.symptomChipText,
                        isSelected && styles.symptomChipTextSelected,
                      ]}
                    >
                      {symptom}
                    </Text>
                  </TouchableOpacity>
                );
              })}
            </View>

            <Text style={styles.fieldLabel}>{t('add_custom_symptoms')}tom Symptoms</Text>
            <Input
              label="Custom symptoms"
              placeholder={t('type_one_or_more_symptoms_sepa')}
              value={symptomDraft}
              onChangeText={(value) => {
                setSymptomDraft(value);
                setValidationMessage("");
              }}
              error={validationMessage || undefined}
              helperText="Example: chest discomfort, dizziness"
              multiline
              numberOfLines={3}
              rightIcon={
                <Plus
                  size={theme.iconSizes.sm}
                  color={healthColors.primary.main}
                />
              }
              onSubmitEditing={handleAddCustomSymptoms}
              blurOnSubmit={false}
            />

            <View style={styles.addButtonWrap}>
              <Button
                variant="outline"
                title="Add Symptoms"
                onPress={handleAddCustomSymptoms}
                icon={
                  <Plus
                    size={theme.iconSizes.sm}
                    color={healthColors.primary.main}
                  />
                }
              />
            </View>

            {!!selectedSymptoms.length && (
              <>
                <Text style={styles.fieldLabel}>{t('selected_symptoms')}</Text>
                <View style={styles.selectedSymptomsWrap}>
                  {selectedSymptoms.map((symptom) => (
                    <View key={symptom} style={styles.selectedSymptomPill}>
                      <Text
                        style={styles.selectedSymptomText}
                        numberOfLines={1}
                        ellipsizeMode="tail"
                      >
                        {symptom}
                      </Text>
                      <TouchableOpacity
                        onPress={() => handleRemoveSymptom(symptom)}
                        accessibilityRole="button"
                        accessibilityLabel={`Remove ${symptom}`}
                        hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
                      >
                        <X
                          size={theme.iconSizes.xs}
                          color={healthColors.text.secondary}
                        />
                      </TouchableOpacity>
                    </View>
                  ))}
                </View>
              </>
            )}

            <Text style={styles.fieldLabel}>{t('duration')}</Text>
            <Input
              label="Duration"
              placeholder={t('how_long_have_you_had_these_sy')}
              value={duration}
              onChangeText={(value) => {
                setDuration(value);
                setResults(null);
              }}
              helperText="Duration helps improve result relevance"
            />

            <Text style={styles.fieldLabel}>{t('severity')}</Text>
            <View style={styles.severityRow}>
              {SEVERITY_OPTIONS.map((item) => {
                const active = severity === item.value;
                return (
                  <TouchableOpacity
                    key={item.value}
                    style={[
                      styles.severityChip,
                      active && {
                        borderColor: item.color,
                        backgroundColor: theme.withOpacity(item.color, 0.08),
                      },
                    ]}
                    onPress={() => {
                      setSeverity(item.value);
                      setResults(null);
                    }}
                    accessibilityRole="button"
                    accessibilityLabel={`Set severity to ${item.label}`}
                    accessibilityState={{ selected: active }}
                  >
                    <Text
                      style={[
                        styles.severityText,
                        active && { color: item.color },
                      ]}
                    >
                      {item.label}
                    </Text>
                  </TouchableOpacity>
                );
              })}
            </View>

            <View style={styles.ctaRow}>
              <Button
                title="Analyze Symptoms"
                onPress={handleAnalyze}
                disabled={!isFormReady || analysisMutation.isPending}
                loading={analysisMutation.isPending}
                icon={
                  <Sparkles
                    size={theme.iconSizes.sm}
                    color={healthColors.text.white}
                  />
                }
                style={styles.primaryCta}
              />
              <Button
                variant="outline"
                title="Clear Form"
                onPress={handleClearAll}
                style={styles.secondaryCta}
              />
            </View>

            <View style={styles.noteBox}>
              <Info
                size={theme.iconSizes.xs}
                color={healthColors.text.secondary}
              />
              <Text style={styles.noteText}>
                {t('ai_results_are_advisory_only_a')} Always consult a licensed
                clinician for diagnosis.
              </Text>
            </View>
          </Card>

          <Card style={styles.sectionCard}>
            <SectionHeader title="2. AI Results" />

            {analysisMutation.isPending ? (
              <View style={styles.loadingBlock}>
                <ActivityIndicator
                  size="large"
                  color={healthColors.primary.main}
                />
                <Text style={styles.loadingText}>
                  {t('analyzing_your_symptoms')}..
                </Text>
              </View>
            ) : !results ? (
              <EmptyState
                icon={AIIcon}
                title="Enter symptoms to begin"
                message="Add one or more symptoms, choose severity, and tap Analyze Symptoms."
              />
            ) : (
              <View style={styles.resultsBlock}>
                {conditionList.map((condition, index) => (
                  <Card
                    key={`${condition?.name || "condition"}-${index}`}
                    elevation="small"
                    style={styles.conditionCard}
                  >
                    <View style={styles.conditionTopRow}>
                      <View style={styles.rankPill}>
                        <Text style={styles.rankText}>#{index + 1}</Text>
                      </View>
                      <Text style={styles.conditionName} numberOfLines={2}>
                        {condition?.name || "Unknown"}
                      </Text>
                      <Text style={styles.probabilityText}>
                        {condition?.probability || 0}%
                      </Text>
                    </View>

                    <View style={styles.progressTrack}>
                      <View
                        style={[
                          styles.progressFill,
                          {
                            width: `${Math.max(
                              0,
                              Math.min(100, condition?.probability || 0)
                            )}%`,
                          },
                        ]}
                      />
                    </View>
                  </Card>
                ))}

                <View style={styles.metaCard}>
                  <View style={styles.metaRow}>
                    <AlertTriangle
                      size={theme.iconSizes.sm}
                      color={
                        results?.urgencyLevel === "high"
                          ? healthColors.error.main
                          : healthColors.warning.main
                      }
                    />
                    <Text style={styles.metaLabel}>{t('urgency')}</Text>
                    <Text style={styles.metaValue}>
                      {String(results?.urgencyLevel || "medium").toUpperCase()}
                    </Text>
                  </View>

                  <View style={styles.metaRow}>
                    <Clock
                      size={theme.iconSizes.sm}
                      color={healthColors.primary.main}
                    />
                    <Text style={styles.metaLabel}>{t('estimated_recovery')}</Text>
                    <Text style={styles.metaValue}>
                      {results?.estimatedRecovery || "N/A"}
                    </Text>
                  </View>
                </View>

                {!!results?.recommendations?.length && (
                  <View style={styles.listSection}>
                    <Text style={styles.subSectionTitle}>{t('recommendations')}</Text>
                    {results.recommendations.map((item, index) => (
                      <View key={`rec-${index}`} style={styles.listRow}>
                        <CheckCircle2
                          size={theme.iconSizes.xs}
                          color={healthColors.success.main}
                        />
                        <Text style={styles.listText}>{item}</Text>
                      </View>
                    ))}
                  </View>
                )}

                {!!results?.whenToSeekHelp?.length && (
                  <View style={styles.alertPanel}>
                    <Text style={styles.subSectionTitle}>
                      {t('seek_immediate_help_if')}
                    </Text>
                    {results.whenToSeekHelp.map((item, index) => (
                      <View key={`warn-${index}`} style={styles.listRow}>
                        <AlertTriangle
                          size={theme.iconSizes.xs}
                          color={healthColors.error.main}
                        />
                        <Text style={styles.alertText}>{item}</Text>
                      </View>
                    ))}
                  </View>
                )}
              </View>
            )}
          </Card>

          <Card style={styles.sectionCard}>
            <SectionHeader
              title="3. Disease Info"
              actionLabel="Open Full Center"
              onAction={() => navigation.navigate(Routes.PATIENT.DISEASE_INFO)}
            />

            {!topCondition ? (
              <EmptyState
                icon={Stethoscope}
                title="No disease profile yet"
                message="Run analysis to see a structured overview for the top likely condition."
              />
            ) : (
              <View style={styles.diseaseInfoBlock}>
                <Text style={styles.diseaseName}>{topCondition.name}</Text>

                <View style={styles.infoSection}>
                  <Text style={styles.infoHeading}>{t('overview')}</Text>
                  <Text style={styles.infoBody}>{diseaseInfo.overview}</Text>
                </View>

                <View style={styles.infoSection}>
                  <Text style={styles.infoHeading}>{t('symptoms')}</Text>
                  {diseaseInfo.symptoms.map((item) => (
                    <Text key={`sym-${item}`} style={styles.infoListItem}>
                      • {item}
                    </Text>
                  ))}
                </View>

                <View style={styles.infoSection}>
                  <Text style={styles.infoHeading}>{t('causes')}es</Text>
                  {diseaseInfo.causes.map((item) => (
                    <Text key={`cause-${item}`} style={styles.infoListItem}>
                      • {item}
                    </Text>
                  ))}
                </View>

                <View style={styles.infoSection}>
                  <Text style={styles.infoHeading}>{t('treatment')}ment</Text>
                  {diseaseInfo.treatment.map((item) => (
                    <Text key={`treat-${item}`} style={styles.infoListItem}>
                      • {item}
                    </Text>
                  ))}
                </View>
              </View>
            )}
          </Card>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: healthColors.background.primary,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: getScreenPadding(),
    paddingBottom: theme.spacing.md,
    minHeight: theme.spacing.xxxxl,
    backgroundColor: healthColors.background.card,
    borderBottomWidth: 1,
    borderBottomColor: healthColors.border.light,
  },
  headerButton: {
    width: theme.touchTargets.md,
    height: theme.touchTargets.md,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitleWrap: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: theme.spacing.sm,
  },
  headerTitle: {
    fontSize: theme.typography.sizes.xl,
    fontWeight: theme.typography.weights.bold,
    color: healthColors.text.primary,
    textAlign: "center",
  },
  headerSubtitle: {
    marginTop: theme.spacing.xs,
    fontSize: theme.typography.sizes.caption,
    color: healthColors.text.secondary,
    textAlign: "center",
    lineHeight: theme.typography.sizes.bodySmall + 4,
    paddingHorizontal: theme.spacing.xs,
  },
  scrollContent: {
    flexGrow: 1,
  },
  contentColumn: {
    width: "100%",
    maxWidth: 960,
    alignSelf: "center",
    paddingHorizontal: getScreenPadding(),
    paddingTop: theme.spacing.md,
    gap: theme.spacing.md,
  },
  sectionCard: {
    borderRadius: theme.borderRadius.card,
  },
  fieldLabel: {
    marginBottom: theme.spacing.xs,
    fontSize: theme.typography.sizes.bodyMedium,
    fontWeight: theme.typography.weights.semibold,
    color: healthColors.text.primary,
  },
  symptomGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
  symptomChip: {
    minHeight: theme.touchTargets.md,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.borderRadius.full,
    borderWidth: 1,
    borderColor: healthColors.border.light,
    backgroundColor: healthColors.background.card,
    justifyContent: "center",
  },
  symptomChipSelected: {
    borderColor: healthColors.primary.main,
    backgroundColor: theme.withOpacity(healthColors.primary.main, 0.08),
  },
  symptomChipText: {
    fontSize: theme.typography.sizes.bodyMedium,
    color: healthColors.text.secondary,
  },
  symptomChipTextSelected: {
    color: healthColors.primary.main,
    fontWeight: theme.typography.weights.semibold,
  },
  addButtonWrap: {
    marginTop: theme.spacing.xs,
    marginBottom: theme.spacing.sm,
    alignItems: "flex-start",
  },
  selectedSymptomsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
  selectedSymptomPill: {
    maxWidth: "100%",
    minHeight: theme.touchTargets.md,
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.xs,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.borderRadius.full,
    borderWidth: 1,
    borderColor: healthColors.border.light,
    backgroundColor: healthColors.background.secondary,
  },
  selectedSymptomText: {
    flexShrink: 1,
    fontSize: theme.typography.sizes.bodySmall,
    color: healthColors.text.primary,
    fontWeight: theme.typography.weights.medium,
  },
  severityRow: {
    flexDirection: "row",
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
  severityChip: {
    flex: 1,
    minHeight: theme.touchTargets.md,
    borderWidth: 1,
    borderColor: healthColors.border.light,
    borderRadius: theme.borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: healthColors.background.card,
  },
  severityText: {
    fontSize: theme.typography.sizes.bodyMedium,
    color: healthColors.text.secondary,
    fontWeight: theme.typography.weights.medium,
  },
  ctaRow: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
  },
  primaryCta: {
    width: "100%",
  },
  secondaryCta: {
    width: "100%",
  },
  noteBox: {
    marginTop: theme.spacing.md,
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    backgroundColor: healthColors.background.secondary,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: theme.spacing.sm,
  },
  noteText: {
    flex: 1,
    fontSize: theme.typography.sizes.caption,
    color: healthColors.text.secondary,
    lineHeight: theme.typography.sizes.bodyMedium + 4,
  },
  loadingBlock: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 180,
    gap: theme.spacing.sm,
  },
  loadingText: {
    fontSize: theme.typography.sizes.bodyMedium,
    color: healthColors.text.secondary,
  },
  resultsBlock: {
    gap: theme.spacing.sm,
  },
  conditionCard: {
    borderRadius: theme.borderRadius.md,
  },
  conditionTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
  },
  rankPill: {
    minWidth: theme.spacing.xl,
    height: theme.spacing.xl,
    borderRadius: theme.borderRadius.full,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.withOpacity(healthColors.primary.main, 0.1),
  },
  rankText: {
    fontSize: theme.typography.sizes.caption,
    fontWeight: theme.typography.weights.bold,
    color: healthColors.primary.main,
  },
  conditionName: {
    flex: 1,
    minWidth: 0,
    fontSize: theme.typography.sizes.bodyLarge,
    color: healthColors.text.primary,
    fontWeight: theme.typography.weights.semibold,
  },
  probabilityText: {
    minWidth: 48,
    textAlign: "right",
    fontSize: theme.typography.sizes.bodyMedium,
    color: healthColors.primary.main,
    fontWeight: theme.typography.weights.bold,
  },
  progressTrack: {
    height: theme.spacing.xs + 2,
    borderRadius: theme.borderRadius.full,
    backgroundColor: healthColors.background.secondary,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: healthColors.primary.main,
  },
  metaCard: {
    marginTop: theme.spacing.xs,
    borderWidth: 1,
    borderColor: healthColors.border.light,
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing.md,
    gap: theme.spacing.sm,
    backgroundColor: healthColors.background.card,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  metaLabel: {
    flex: 1,
    fontSize: theme.typography.sizes.bodyMedium,
    color: healthColors.text.secondary,
  },
  metaValue: {
    fontSize: theme.typography.sizes.bodyMedium,
    color: healthColors.text.primary,
    fontWeight: theme.typography.weights.semibold,
  },
  listSection: {
    marginTop: theme.spacing.xs,
    gap: theme.spacing.xs,
  },
  subSectionTitle: {
    fontSize: theme.typography.sizes.bodyMedium,
    color: healthColors.text.primary,
    fontWeight: theme.typography.weights.semibold,
  },
  listRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: theme.spacing.sm,
  },
  listText: {
    flex: 1,
    fontSize: theme.typography.sizes.bodyMedium,
    color: healthColors.text.secondary,
    lineHeight: theme.typography.sizes.bodyLarge + 4,
  },
  alertPanel: {
    marginTop: theme.spacing.xs,
    borderWidth: 1,
    borderColor: theme.withOpacity(healthColors.error.main, 0.25),
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing.md,
    backgroundColor: theme.withOpacity(healthColors.error.main, 0.06),
    gap: theme.spacing.xs,
  },
  alertText: {
    flex: 1,
    fontSize: theme.typography.sizes.bodyMedium,
    color: healthColors.error.dark,
    lineHeight: theme.typography.sizes.bodyLarge + 4,
  },
  diseaseInfoBlock: {
    gap: theme.spacing.sm,
  },
  diseaseName: {
    fontSize: theme.typography.sizes.lg,
    color: healthColors.text.primary,
    fontWeight: theme.typography.weights.bold,
  },
  infoSection: {
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    backgroundColor: healthColors.background.secondary,
    gap: theme.spacing.xs,
  },
  infoHeading: {
    fontSize: theme.typography.sizes.bodyMedium,
    fontWeight: theme.typography.weights.semibold,
    color: healthColors.text.primary,
  },
  infoBody: {
    fontSize: theme.typography.sizes.bodyMedium,
    color: healthColors.text.secondary,
    lineHeight: theme.typography.sizes.bodyLarge + 4,
  },
  infoListItem: {
    fontSize: theme.typography.sizes.bodyMedium,
    color: healthColors.text.secondary,
    lineHeight: theme.typography.sizes.bodyLarge + 4,
  },
});

export default AISymptomChecker;
